packages:
  - .
  - packages/*
  - docs

ignoreWorkspaceRootCheck: true

allowBuilds:
  esbuild: true
  sharp: true
  workerd: true

peerDependencyRules:
  allowedVersions:
    starlight-contextual-menu>astro: "7"
